---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-mirrored-pair-volume.html 
sidebar: sidebar 
keywords: change, settings, mirrored, pair, volume, adjust, percentage, point, system, manager, alert, notification, reserved, capacity, full 
summary: 'Vous pouvez modifier les paramètres d"un volume de paire en miroir pour ajuster le point de pourcentage auquel System Manager envoie une notification d"alerte lorsque la capacité réservée d"un volume de paire en miroir est presque pleine.' 
---
= Modifiez les paramètres de capacité réservée pour un volume de paire en miroir
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les paramètres d'un volume de paire en miroir pour ajuster le point de pourcentage auquel System Manager envoie une notification d'alerte lorsque la capacité réservée d'un volume de paire en miroir est presque pleine.

.Étapes
. Menu Sélectionner:Storage[pools & Volume Groups].
. Sélectionnez l'onglet *capacité réservée*.
. Sélectionnez le volume de paires symétriques que vous souhaitez modifier, puis cliquez sur *Afficher/Modifier les paramètres*.
+
La boîte de dialogue *Paramètres de capacité réservée du volume de paire en miroir* s'affiche.

. Modifiez les paramètres de capacité réservée pour le volume de paire en miroir selon les besoins.
+
.Détails du champ
[%collapsible]
====
[cols="1a,3a"]
|===
| Réglage | Description 


 a| 
M'avertir lorsque...
 a| 
Utilisez la boîte à plateau pour régler le point de pourcentage auquel System Manager envoie une notification d'alerte lorsque la capacité réservée d'une paire en miroir est presque pleine.

Lorsque la capacité réservée de la paire en miroir dépasse le seuil spécifié, System Manager envoie une alerte et vous permet d'augmenter la capacité réservée.


NOTE: La modification du paramètre alerte pour une paire symétrique modifie le paramètre alerte pour toutes les paires symétriques appartenant au même groupe de cohérence miroir.



 a| 
Règle pour la capacité totale réservée
 a| 
Vous pouvez choisir l'une des règles suivantes :

** *Purge de l'image snapshot la plus ancienne* – System Manager purge automatiquement l'image snapshot la plus ancienne du groupe de cohérence, ce qui libère la capacité réservée du membre pour réutilisation au sein du groupe.
** *Rejeter les écritures sur le volume de base* – lorsque la capacité réservée atteint son pourcentage maximal défini, System Manager rejette toute demande d'écriture d'E/S au volume de base qui a déclenché l'accès à la capacité réservée.


|===
====
. Cliquez sur *Enregistrer* pour appliquer vos modifications.


.Résultat
System Manager modifie les paramètres de capacité réservée pour le volume membre, ainsi que les paramètres de capacité réservée pour tous les volumes membres du groupe de cohérence.
