---
permalink: sm-storage/how-does-my-selected-workload-impact-volume-creation.html 
sidebar: sidebar 
keywords: workload, storage, object, support, application, define, more, instance, system, manager, configure, contain, volumes, similar, underlying, characteristics, optimized, based, type, support, example, create, server, subsequently, underlying 
summary: 'Un workload est un objet de stockage qui prend en charge une application. Vous pouvez définir une ou plusieurs charges de travail ou instances par application. System Manager configure parfois la charge de travail de manière à contenir des volumes dont les caractéristiques des volumes sous-jacents sont similaires. Ces caractéristiques de volume sont optimisées en fonction du type d"application pris en charge par les workloads. Par exemple, si vous créez une charge de travail prenant en charge une application Microsoft SQL Server, puis que vous créez des volumes pour cette charge de travail, les caractéristiques du volume sous-jacent sont optimisées pour prendre en charge Microsoft SQL Server.' 
---
= Comment les charges de travail sélectionnées affectent-elles la création du volume ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un workload est un objet de stockage qui prend en charge une application. Vous pouvez définir une ou plusieurs charges de travail ou instances par application. System Manager configure parfois la charge de travail de manière à contenir des volumes dont les caractéristiques des volumes sous-jacents sont similaires. Ces caractéristiques de volume sont optimisées en fonction du type d'application pris en charge par les workloads. Par exemple, si vous créez une charge de travail prenant en charge une application Microsoft SQL Server, puis que vous créez des volumes pour cette charge de travail, les caractéristiques du volume sous-jacent sont optimisées pour prendre en charge Microsoft SQL Server.

* *Spécifique à l'application*. Lorsque vous créez des volumes à l'aide d'une charge de travail spécifique à l'application, le système peut recommander une configuration de volume optimisée afin de limiter les conflits entre les E/S de charge de travail d'application et tout autre trafic de votre instance d'application. Les caractéristiques de volume comme le type d'E/S, la taille de segment, la propriété des contrôleurs et le cache de lecture et d'écriture sont automatiquement recommandées et optimisées pour les charges de travail créées pour les types d'applications suivants.
+
** Microsoft® SQL Server™
** Microsoft® Exchange Server™
** Applications de vidéosurveillance
** VMware ESXi ™ (pour les volumes à utiliser avec Virtual machine File System) vous pouvez vérifier la configuration de volume recommandée et modifier, ajouter ou supprimer les volumes et les caractéristiques recommandés par le système à l'aide de la boîte de dialogue *Ajouter/Modifier volumes*.


* *Autre* (ou applications sans support de création de volume spécifique). D'autres charges de travail utilisent une configuration de volume que vous devez spécifier manuellement lorsque vous souhaitez créer un workload non associé à une application spécifique ou si System Manager n'a pas d'optimisation intégrée pour l'application que vous prévoyez d'utiliser sur la baie de stockage. Vous devez spécifier manuellement la configuration du volume à l'aide de la boîte de dialogue *Ajouter/Modifier volumes*.

