---
permalink: sm-mirroring/why-cant-i-access-my-chosen-mirroring-feature.html 
sidebar: sidebar 
keywords: mirror, configure, unified, manager 
summary: 'La mise en miroir est configurée dans l"interface Unified Manager.' 
---
= Pourquoi ne puis-je pas accéder à la fonction de mise en miroir choisie ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La mise en miroir est configurée dans l'interface Unified Manager.

Pour activer et configurer la mise en miroir entre deux baies, vérifiez les points suivants :

* Le service Web Services Proxy doit être en cours d'exécution. (Unified Manager est installé sur un système hôte avec le proxy de services Web.)
* Unified Manager doit s'exécuter sur votre hôte local via une connexion HTTPS.
* Les deux baies de stockage que vous souhaitez utiliser pour la mise en miroir doivent être découvertes dans Unified Manager.
* Unified Manager doit disposer de certificats SSL valides pour les matrices de stockage. Vous pouvez accepter un certificat auto-signé ou installer des certificats avec une autorité de certification depuis Unified Manager.


Pour plus d'informations sur les exigences, consultez l'aide en ligne de Unified Manager.

[NOTE]
====
La mise en miroir n'est pas disponible sur la baie de stockage EF600.

====