---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: configure, storage, array, administrator, password, protect, unauthorize, access 
summary: Vous devez configurer la matrice de stockage avec un mot de passe administrateur pour la protéger contre les accès non autorisés. 
---
= Protection par mot de passe de l'administrateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer la matrice de stockage avec un mot de passe administrateur pour la protéger contre les accès non autorisés.



== Définition d'un mot de passe administrateur

La définition d'un mot de passe d'administrateur pour votre matrice de stockage le protège des utilisateurs qui exécutent des commandes destructives de manière involontaire ou malveillante. Lorsque vous démarrez System Manager pour la première fois, vous devez définir un mot de passe d'administrateur.

Un mot de passe administrateur est partagé entre tous les utilisateurs. Tout utilisateur disposant de ce mot de passe peut modifier la configuration de la matrice de stockage, comme l'ajout, la modification ou la suppression d'objets ou de paramètres.



== Saisissez votre mot de passe

Le système vous demande le mot de passe une seule fois lors d'une seule session de gestion. Une session est expirée au bout de 20 minutes d'inactivité. Vous devez alors saisir à nouveau le mot de passe.

Si un autre utilisateur gérant la même matrice de stockage à partir d'un autre client de gestion modifie le mot de passe pendant que votre session est en cours, vous êtes invité à saisir un mot de passe lors de la prochaine tentative d'opération de configuration ou d'affichage.

Pour des raisons de sécurité, vous ne pouvez tenter de saisir un mot de passe que cinq fois avant que la matrice de stockage ne passe à l'état « verrouillage ». Dans cet état, la matrice de stockage rejette les tentatives de mot de passe suivantes. Vous devez attendre 10 minutes que la matrice de stockage se réinitialise à l'état « normal » avant d'essayer à nouveau d'entrer un mot de passe.



== Retrait de disques avec protection par mot de passe

Le mot de passe est stocké dans une zone réservée de chaque lecteur de la matrice de stockage. Si vous supprimez tous les disques d'une matrice de stockage, son mot de passe ne fonctionnera plus. Pour corriger ce problème, réinstallez l'un des disques d'origine sur la matrice de stockage.



== Suppression de la protection par mot de passe

Si vous ne souhaitez plus que les commandes soient protégées par un mot de passe, entrez le mot de passe administrateur actuel et laissez les zones de texte du nouveau mot de passe vides.

[NOTE]
====
L'exécution de commandes de configuration sur une matrice de stockage peut causer des dommages graves, y compris la perte de données. C'est pourquoi vous devez toujours définir un mot de passe administrateur pour votre matrice de stockage. Pour renforcer la sécurité, utilisez un mot de passe administrateur long comportant au moins 15 caractères alphanumériques.

====