---
permalink: sm-interface/view-and-act-on-operations-in-progress.html 
sidebar: sidebar 
keywords: view, action, long-run, operations, progress 
summary: Pour afficher et prendre des mesures sur les opérations à long terme, utilisez la page opérations en cours. 
---
= Voir et agir sur les opérations en cours
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour afficher et prendre des mesures sur les opérations à long terme, utilisez la page opérations en cours.

Pour chaque opération répertoriée sur la page opérations en cours, un pourcentage d'achèvement et une estimation du temps restant pour terminer l'opération sont indiqués. Dans certains cas, vous pouvez arrêter une opération ou la placer à une priorité plus ou moins élevée. Vous pouvez également effacer une opération de copie de volume terminée de la liste.

.Étapes
. Sur la page *Accueil*, sélectionnez *Afficher les opérations en cours*.
+
La page *opérations en cours* s'affiche.

. Si vous le souhaitez, utilisez les liens de la colonne *actions* pour arrêter ou modifier la priorité d'une opération.
+
[CAUTION]
====
Lisez tous les textes de mise en garde fournis dans les boîtes de dialogue, en particulier lors de l'arrêt d'une opération.

====
+
Vous pouvez arrêter une opération de copie de volume ou modifier sa priorité.

. Une fois l'opération de copie de volume terminée, vous pouvez sélectionner *Effacer* pour la supprimer de la liste.
+
En haut de la page *Home*, un message d'information et une icône de clé jaune s'affichent lorsque l'opération est terminée. Ce message comprend un lien qui vous permet de supprimer l'opération de la page *opérations en cours*.


