---
permalink: sm-settings/add-community-names-for-snmp-traps.html 
sidebar: sidebar 
keywords: add up, community, snmp traps 
summary: 'Vous pouvez ajouter jusqu"à 256 noms de communauté pour les interruptions SNMP.' 
---
= Ajouter des noms de communauté pour les interruptions SNMP
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter jusqu'à 256 noms de communauté pour les interruptions SNMP.

.Avant de commencer
Le ou les noms de communauté doivent être créés. Le nom de communauté, qui est une chaîne qui agit comme un mot de passe pour les serveurs réseau, est généralement créé par un administrateur réseau. Il se compose uniquement de caractères ASCII imprimables.

.Étapes
. Sélectionnez *menu:Paramètres[alertes]*.
. Sélectionnez l'onglet *SNMP*.
+
Les destinations d'interruption et les noms de communauté apparaissent dans le tableau.

. Sélectionnez *configurer les communautés*.
+
La boîte de dialogue configurer les communautés s'ouvre.

. Sélectionnez *Ajouter une autre communauté*.
. Entrez le nouveau nom de communauté, puis cliquez sur *Enregistrer*.


.Résultats
Le nouveau nom de communauté apparaît dans l'onglet *SNMP* de la page *alertes*.
