---
permalink: sm-settings/configure-snmp-alerts.html 
sidebar: sidebar 
keywords: configuration, snmp alerts, identification, one server, storage array, snmp traps, community name, ip address 
summary: 'Pour configurer les alertes SNMP (simple Network Management Protocol), vous devez identifier au moins un serveur sur lequel le moniteur d"événements de la baie de stockage peut envoyer des interruptions SNMP. La configuration requiert un nom de communauté et une adresse IP pour le serveur.' 
---
= Configuration des communautés et destinations des alertes SNMP
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour configurer les alertes SNMP (simple Network Management Protocol), vous devez identifier au moins un serveur sur lequel le moniteur d'événements de la baie de stockage peut envoyer des traps SNMP. La configuration requiert un nom de communauté et une adresse IP pour le serveur.

.Avant de commencer
* Un serveur réseau doit être configuré avec une application de service SNMP. Vous avez besoin de l'adresse réseau de ce serveur (soit une adresse IPv4, soit une adresse IPv6), de sorte que le moniteur d'événements puisse envoyer des messages d'interruption à cette adresse. Vous pouvez utiliser plusieurs serveurs (jusqu'à 10 serveurs sont autorisés).
* Un nom de communauté doit être créé, composé uniquement de caractères ASCII imprimables. Le nom de communauté, qui est une chaîne qui agit comme un mot de passe pour les serveurs réseau, est généralement créé par un administrateur réseau. Il est possible de créer jusqu'à 256 communautés.
* Le fichier MIB (Management information base) a été copié et compilé sur le serveur avec l'application de service SNMP. Ce fichier MIB définit les données en cours de contrôle et de gestion.
+
Si vous ne possédez pas le fichier MIB, vous pouvez l'obtenir sur le site de support NetApp :

+
** Accédez à https://mysupport.netapp.com/site/["Support NetApp"^].
** Cliquez sur *Téléchargements*.
** Cliquez sur *logiciel*.
** Recherchez votre logiciel de gestion (par exemple, SANtricity System Manager), puis cliquez sur *Go!* à droite.
** Cliquez sur** Voir et télécharger sur la dernière version.
** Cliquez sur *Continuer* en bas de la page.
** Acceptez le CLUF.
** Faites défiler vers le bas jusqu'à ce que vous voyez le fichier *MIB pour les interruptions SNMP*, puis cliquez sur le lien pour télécharger le fichier.




Cette tâche décrit comment identifier le serveur SNMP pour les destinations de déroutement, puis tester votre configuration.

.Étapes
. Sélectionnez *menu:Paramètres[alertes]*.
. Sélectionnez l'onglet *SNMP*.
+
Si une communauté n'est pas encore configurée, l'onglet SNMP affiche « configurer les communautés ».

. Sélectionnez *configurer les communautés*.
+
La boîte de dialogue *configurer les communautés* s'ouvre.

. Dans le champ *Nom de communauté*, entrez une ou plusieurs chaînes de communauté pour les serveurs réseau, puis cliquez sur *Enregistrer*.
+
La page alertes affiche « Ajouter des destinations de déroutement ».

. Sélectionnez *Ajouter des destinations de recouvrement*.
+
La boîte de dialogue *Ajouter des destinations de recouvrement* s'ouvre.

. Entrez une ou plusieurs destinations d'interruption, sélectionnez leurs noms de communauté associés, puis cliquez sur *Ajouter*.
+
** *Trap destination* -- Entrez une adresse IPv4 ou IPv6 du serveur exécutant un service SNMP.
** *Nom de communauté* -- dans la liste déroulante, sélectionnez le nom de communauté pour cette destination de déroutement. (Si vous avez défini un seul nom de communauté, le nom apparaît déjà dans ce champ.)
** *Send Authentication Failure Trap* -- sélectionnez cette option (la case à cocher) si vous souhaitez alerter la destination de l'interruption lorsqu'une requête SNMP est rejetée en raison d'un nom de communauté non reconnu. Après avoir cliqué sur *Ajouter*, les destinations de déroutement et les noms de communauté associés apparaissent dans l'onglet *SNMP* de la page *alertes*.


. Pour vous assurer qu'une interruption est valide, sélectionnez une destination d'interruption dans le tableau, puis cliquez sur *Test Trap destination* pour envoyer une interruption de test à l'adresse configurée.


Le moniteur d'événements envoie des interruptions SNMP au(x) serveur(s) chaque fois qu'un événement alertable se produit.
