---
permalink: sm-settings/configure-snmp-mib-variables.html 
sidebar: sidebar 
keywords: snmp alerts, optional, mib, variables, snmp traps, storage array, contact person 
summary: 'Pour les alertes SNMP, vous pouvez éventuellement configurer les variables MIB (Management information base) qui apparaissent dans les traps SNMP. Ces variables peuvent renvoyer le nom de la matrice de stockage, l"emplacement de la matrice et une personne à contacter.' 
---
= Configurer les variables MIB SNMP
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour les alertes SNMP, vous pouvez éventuellement configurer les variables MIB (Management information base) qui apparaissent dans les traps SNMP. Ces variables peuvent renvoyer le nom de la matrice de stockage, l'emplacement de la matrice et une personne à contacter.

Le fichier MIB doit être copié et compilé sur le serveur avec l'application de service SNMP.

Si vous n'avez pas de fichier MIB, vous pouvez l'obtenir comme suit:

* Accédez à https://mysupport.netapp.com/site/["Support NetApp"^].
* Cliquez sur *Téléchargements*.
* Cliquez sur *logiciel*.
* Recherchez votre logiciel de gestion (par exemple, SANtricity System Manager), puis cliquez sur *Go!* à droite.
* Cliquez sur *View & Download* sur la dernière version.
* Cliquez sur *Continuer* en bas de la page.
* Acceptez le CLUF.
* Faites défiler vers le bas jusqu'à ce que vous voyez le fichier *MIB pour les interruptions SNMP*, puis cliquez sur le lien pour télécharger le fichier.


Cette tâche décrit comment définir des variables MIB pour les interruptions SNMP. Ces variables peuvent renvoyer les valeurs suivantes en réponse à SNMP GetRequests :

* `_sysName_` (nom de la matrice de stockage)
* `_sysLocation_` (emplacement de la baie de stockage)
* `_sysContact_` (nom d'un administrateur)


.Étapes
. Sélectionnez *menu:Paramètres[alertes]*.
. Sélectionnez l'onglet *SNMP*.
. Sélectionnez *configurer les variables MIB SNMP*.
+
La boîte de dialogue configurer les variables MIB SNMP s'ouvre.

. Entrez une ou plusieurs des valeurs suivantes, puis cliquez sur *Enregistrer*.
+
** *Nom* -- la valeur de la variable MIB `_sysName_`. Par exemple, entrez un nom pour la matrice de stockage.
** *Location* -- la valeur de la variable MIB `_sysLocation_`. Par exemple, entrez un emplacement de la matrice de stockage.
** *Contact* -- la valeur de la variable MIB `_sysContact_`. Par exemple, entrez un administrateur responsable de la matrice de stockage.




Ces valeurs apparaissent dans les messages d'interruption SNMP relatifs aux alertes de la baie de stockage.
