---
permalink: sm-settings/remove-directory-server.html 
sidebar: sidebar 
keywords: break, connection, directory, storage array, perform task, remove, old, one, access management 
summary: 'Pour interrompre la connexion entre un serveur d"annuaire et la matrice de stockage, vous pouvez supprimer les informations sur le serveur de la page gestion des accès. Vous pouvez effectuer cette tâche si vous avez configuré un nouveau serveur, puis que vous souhaitez supprimer l"ancien serveur.' 
---
= Supprimer le serveur de répertoire
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour interrompre la connexion entre un serveur d'annuaire et la matrice de stockage, vous pouvez supprimer les informations sur le serveur de la page gestion des accès. Vous pouvez effectuer cette tâche si vous avez configuré un nouveau serveur, puis que vous souhaitez supprimer l'ancien serveur.

.Avant de commencer
* Vous devez être connecté avec un profil utilisateur qui inclut les autorisations d'administrateur de sécurité. Dans le cas contraire, les fonctions de gestion des accès ne s'affichent pas.


.Description de la tâche
Une fois cette tâche terminée, toutes les sessions utilisateur actives sont arrêtées. Seule votre session utilisateur actuelle est conservée.

.Étapes
. Sélectionnez *menu:Paramètres[gestion des accès]*.
. Sélectionnez l'onglet *Services Annuaire*.
. Dans la liste, sélectionnez le serveur de répertoire à supprimer.
. Cliquez sur *Supprimer*.
+
La boîte de dialogue *Remove Directory Server* s'ouvre.

. Type `remove` Dans le champ, puis cliquez sur *Supprimer*.
+
Les paramètres de configuration du serveur d'annuaire, les paramètres de privilèges et les mappages de rôles sont supprimés. Les utilisateurs ne peuvent plus se connecter avec les informations d'identification de ce serveur.


