---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: configure, santricity, unified, manager, administrator, password, protect, unauthorized, access 
summary: 'Vous devez configurer SANtricity Unified Manager avec un mot de passe d"administrateur pour le protéger contre tout accès non autorisé.' 
---
= Protection par mot de passe de l'administrateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer SANtricity Unified Manager avec un mot de passe d'administrateur pour le protéger contre tout accès non autorisé.



== Définition d'un mot de passe administrateur

La définition d'un mot de passe administrateur protège le logiciel des utilisateurs qui exécutent des commandes destructives de manière involontaire ou malveillante. Lorsque vous démarrez Unified Manager pour la première fois, vous devez définir un mot de passe d'administrateur.

Un mot de passe administrateur est partagé entre tous les utilisateurs. Tout utilisateur possédant ce mot de passe peut modifier la configuration des systèmes de stockage.



== Saisissez votre mot de passe

Le logiciel vous demande le mot de passe une seule fois lors d'une seule session de gestion. Une session est expirée au bout de 30 minutes d'inactivité par défaut. Vous devez alors saisir à nouveau le mot de passe. Si vous le souhaitez, vous pouvez régler le délai d'expiration de la session.

Si un autre utilisateur accède au logiciel à partir d'un autre client de gestion et modifie le mot de passe pendant que votre session est en cours, vous êtes invité à saisir un mot de passe lors de la prochaine tentative d'opération de configuration ou d'affichage.

Pour des raisons de sécurité, vous ne pouvez tenter de saisir un mot de passe que cinq fois avant que le logiciel n'entre dans un état de « verrouillage ». Dans cet état, le logiciel rejette les tentatives de mot de passe suivantes. Vous devez attendre 10 minutes pour revenir à l'état « normal » avant d'essayer de saisir à nouveau un mot de passe.
